### ISSUE TITLE
Bug Fix: When the facility list is selected, both select boxes reset but the items available are listed.

### ISSUE THREAD

**Issue by jscott-scates** [NSS-Day-Cohort-74/Exomine-client-mhcjjq#28]

**Comment by ntzeitlin** [comment]
For both the governor and facility drop down menus:

Added an if statement to check whether the selected option's id matches the id held in transient state. If it does match, add a 'selected' attribute to the option element. 

Fixes the problem. 

Additionally, added a resetTransientState function call to the purchase material button for testing purposes.
